title: ダンジョン異世界
description: 異世界の未踏破の地下ダンジョン
show_downloads: false
hide_github: true

collections:
  blog:
    output: true
    permalink: /:title/

buttons:
  - text: ""
    href: "https://github.com/99ndd9/blog/"

remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

url: https://99ndd9.github.io
